# Generated by Django 4.0.6 on 2022-07-21 14:11

from django.db import migrations, models


def create_tickers(apps, schema_editor):
    Ticker = apps.get_model('tickers', 'Ticker')
    for i in range(100):
        if i < 10:
            name_index = '0{0}'.format(i)
        else:
            name_index = '{0}'.format(i)
        Ticker.objects.create(
            name='ticker_{0}'.format(name_index), value=0,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RunPython(create_tickers),
    ]
